### ISSUE TITLE
Верхнее поле

### ISSUE THREAD

**Issue by DmitriyGordon** [DmitriyGordon/iteaMineSweeper#2]
Сгенерировать верхнее игровое поле с задаными размерами.

Под сгенерировать подразумевается создать переменную, которая будет хранить матрицу нашего поля.

Данное поле будет верхним, так как пользователь будет видеть данное поле. В последующем оно будет хранить открытые ячейки(информацию о количестве мин вокруг данной ячейки, а также метки мин).

**Comment by ivchenkomac7** [comment]
Можно ли здесь сгенерировать такую же переменную, как и скрытую,только с другим именем?

**Comment by DmitriyGordon** [comment]
@ivchenkomac7 да конечно, но не присвоив новой переменной старую, а использовать ту же функцию, с помощью которой создавалось первое поле.

**Comment by ivchenkomac7** [comment]
03f2d698007607579e402049a444a846ca51ce6d
