### ISSUE TITLE
Сгенерировать мины

### ISSUE THREAD

**Issue by DmitriyGordon** [DmitriyGordon/iteaMineSweeper#3]
Написать фрагмент кода для расстановки определенного числа мин в пределах нижнего игрового поля.

**Comment by MisterYuriy** [comment]
Привет, я справлюсь с этой задачей!

**Comment by DmitriyGordon** [comment]
https://github.com/DmitriyGordon/iteaMineSweeper/commit/0670e2bac718897b04db342a41e67e9501344ac1
