### ISSUE TITLE
Ввод координат ячейки

### ISSUE THREAD

**Issue by DmitriyGordon** [DmitriyGordon/iteaMineSweeper#5]
Написать функцию которая позволяет пользователю ввести координаты клетки, которую он хочет открыть.

**Comment by pastushenkomaksym** [comment]
Давайте я попробую

**Comment by DmitriyGordon** [comment]
https://github.com/DmitriyGordon/iteaMineSweeper/commit/0670e2bac718897b04db342a41e67e9501344ac1
